-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    inputWidth : IN STD_LOGIC_VECTOR (31 downto 0);
    inputHeight : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln20 : IN STD_LOGIC_VECTOR (31 downto 0);
    select_ln20 : IN STD_LOGIC_VECTOR (31 downto 0);
    convWidth : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln20_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln3_1 : IN STD_LOGIC_VECTOR (95 downto 0);
    mul_ln3 : IN STD_LOGIC_VECTOR (63 downto 0);
    p_cast8_mid145 : IN STD_LOGIC_VECTOR (31 downto 0);
    tmp4_cast_mid167 : IN STD_LOGIC_VECTOR (31 downto 0);
    icmp_ln27_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    coeffs : IN STD_LOGIC_VECTOR (63 downto 0);
    zext_ln25 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_r : IN STD_LOGIC_VECTOR (63 downto 0);
    acc_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_out_ap_vld : OUT STD_LOGIC;
    grp_fu_271_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_271_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_271_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_271_p_ce : OUT STD_LOGIC;
    grp_fu_344_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_344_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_344_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_344_p_ce : OUT STD_LOGIC;
    grp_fu_348_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_348_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_348_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_348_p_ce : OUT STD_LOGIC;
    grp_fu_352_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_352_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_352_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_352_p_ce : OUT STD_LOGIC;
    grp_fu_356_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_356_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_356_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_356_p_ce : OUT STD_LOGIC;
    grp_fu_363_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_363_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_363_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_363_p_ce : OUT STD_LOGIC;
    grp_fu_413_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_413_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_413_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_413_p_ce : OUT STD_LOGIC );
end;


architecture behav of Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv96_0 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv96_1 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state8_pp0_stage1_iter3 : BOOLEAN;
    signal ap_block_state10_pp0_stage1_iter4 : BOOLEAN;
    signal ap_block_state12_pp0_stage1_iter5 : BOOLEAN;
    signal ap_block_state14_pp0_stage1_iter6 : BOOLEAN;
    signal ap_block_state16_pp0_stage1_iter7 : BOOLEAN;
    signal ap_block_state18_pp0_stage1_iter8 : BOOLEAN;
    signal ap_block_state20_pp0_stage1_iter9 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln25_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln25_reg_882 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_882_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln25_cast_fu_241_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln25_cast_reg_832 : STD_LOGIC_VECTOR (33 downto 0);
    signal p_cast8_mid145_cast_fu_245_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast8_mid145_cast_reg_837 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln20_1_cast_fu_249_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln20_1_cast_reg_842 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp4_cast_mid167_cast_fu_253_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp4_cast_mid167_cast_reg_848 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal iChannel_1_reg_858 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten93_load_reg_865 : STD_LOGIC_VECTOR (95 downto 0);
    signal empty_36_fu_306_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_36_reg_870 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln25_fu_316_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln25_reg_875 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln25_reg_882_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_882_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_882_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_882_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_882_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln25_reg_882_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cx_load_reg_886 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten_load_reg_891 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln26_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_896 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_896_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_896_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln23_fu_338_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln23_reg_907 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln23_4_fu_351_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln23_4_reg_912 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln23_4_reg_912_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln23_4_reg_912_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln26_fu_358_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln26_reg_920 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp2_reg_927 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_35_reg_932 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_38_reg_938 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln23_5_fu_390_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln23_5_reg_943 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln23_5_reg_943_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal p_mid1_fu_397_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_mid1_reg_948 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_37_reg_953 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_37_reg_953_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp2_mid1_reg_958 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_mid139_reg_963 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_mid118_reg_969 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_453_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_reg_974 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_39_fu_476_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal empty_39_reg_980 : STD_LOGIC_VECTOR (33 downto 0);
    signal p_mid169_fu_498_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_mid169_reg_985 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_fu_457_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_mid110_reg_990 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_mid120_fu_515_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal p_mid120_reg_995 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_482_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_mid137_reg_1000 : STD_LOGIC_VECTOR (31 downto 0);
    signal cx_cast_fu_567_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal cx_cast_reg_1006 : STD_LOGIC_VECTOR (62 downto 0);
    signal gmem_addr_reg_1011 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln23_1_fu_642_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln23_1_reg_1017 : STD_LOGIC_VECTOR (33 downto 0);
    signal gmem_addr_1_reg_1022 : STD_LOGIC_VECTOR (63 downto 0);
    signal filterValue_reg_1028 : STD_LOGIC_VECTOR (31 downto 0);
    signal filterValue_reg_1028_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal pixelValue_reg_1033 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1_reg_1048 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal sext_ln30_fu_576_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln31_fu_682_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_fu_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_1_fu_717_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal cx_fu_106 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln27_fu_410_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal cy_fu_110 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln26_fu_405_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten_fu_114 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln26_1_fu_421_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal iChannel_fu_118 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln25_fu_381_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten93_fu_122 : STD_LOGIC_VECTOR (95 downto 0);
    signal add_ln25_1_fu_368_p2 : STD_LOGIC_VECTOR (95 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal empty_36_fu_306_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln25_fu_316_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln23_fu_338_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln27_fu_346_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln27_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln23_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln26_1_fu_416_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast11_fu_464_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp4_fu_467_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp4_cast_fu_472_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln26_fu_461_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal select_ln23_2_fu_489_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln23_5_fu_486_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast11_mid1_fu_503_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp4_mid1_fu_506_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp4_cast_mid1_fu_511_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln23_1_fu_494_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal zext_ln23_6_fu_521_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal select_ln23_6_fu_524_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal select_ln23_7_fu_530_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln27_mid2_v_v_v_v_v_fu_536_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln23_2_fu_544_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln23_fu_548_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln27_mid2_v_fu_553_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal sext_ln23_fu_563_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln30_fu_570_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal p_cast7_fu_586_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast8_fu_589_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal select_ln23_1_fu_601_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_cast7_mid1_fu_598_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp3_mid147_fu_610_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp3_fu_592_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln23_fu_606_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast8_mid1_fu_622_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp3_mid1_fu_625_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal select_ln23_3_fu_615_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal select_ln23_8_fu_631_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln23_3_fu_638_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal sext_ln27_1_mid2_v_v_v_v_v_fu_647_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln23_4_fu_654_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln23_2_fu_658_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln27_1_mid2_v_fu_663_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal sext_ln23_1_fu_673_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln31_fu_677_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal grp_fu_698_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal grp_fu_296_ce : STD_LOGIC;
    signal grp_fu_301_ce : STD_LOGIC;
    signal grp_fu_311_ce : STD_LOGIC;
    signal grp_fu_364_ce : STD_LOGIC;
    signal grp_fu_373_ce : STD_LOGIC;
    signal grp_fu_377_ce : STD_LOGIC;
    signal grp_fu_401_ce : STD_LOGIC;
    signal grp_fu_453_ce : STD_LOGIC;
    signal grp_fu_457_ce : STD_LOGIC;
    signal grp_fu_482_ce : STD_LOGIC;
    signal grp_fu_698_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to9 : STD_LOGIC;
    signal ap_done_pending_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Conv2D_HW_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Conv2D_HW_mul_32s_32s_52_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;


    component Conv2D_HW_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_32s_32s_32_2_1_U8 : component Conv2D_HW_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp2_reg_927,
        din1 => inputHeight,
        ce => grp_fu_453_ce,
        dout => grp_fu_453_p2);

    mul_32s_32s_32_2_1_U9 : component Conv2D_HW_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_mid1_reg_948,
        din1 => inputWidth,
        ce => grp_fu_457_ce,
        dout => grp_fu_457_p2);

    mul_32s_32s_32_2_1_U10 : component Conv2D_HW_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp2_mid1_reg_958,
        din1 => inputHeight,
        ce => grp_fu_482_ce,
        dout => grp_fu_482_p2);

    mul_32s_32s_52_2_1_U11 : component Conv2D_HW_mul_32s_32s_52_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 52)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => pixelValue_reg_1033,
        din1 => filterValue_reg_1028_pp0_iter7_reg,
        ce => grp_fu_698_ce,
        dout => grp_fu_698_p2);

    flow_control_loop_pipe_sequential_init_U : component Conv2D_HW_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                acc_fu_102 <= ap_const_lv32_0;
            elsif (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                acc_fu_102 <= acc_1_fu_717_p2;
            end if; 
        end if;
    end process;

    cx_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    cx_fu_106 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln25_reg_882 = ap_const_lv1_0))) then 
                    cx_fu_106 <= add_ln27_fu_410_p2;
                end if;
            end if; 
        end if;
    end process;

    cy_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    cy_fu_110 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln25_reg_882 = ap_const_lv1_0))) then 
                    cy_fu_110 <= select_ln26_fu_405_p3;
                end if;
            end if; 
        end if;
    end process;

    iChannel_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    iChannel_fu_118 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln25_reg_882 = ap_const_lv1_0))) then 
                    iChannel_fu_118 <= select_ln25_fu_381_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten93_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten93_fu_122 <= ap_const_lv96_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln25_reg_882 = ap_const_lv1_0))) then 
                    indvar_flatten93_fu_122 <= add_ln25_1_fu_368_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_114 <= ap_const_lv64_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln25_reg_882 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_114 <= select_ln26_1_fu_421_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln25_reg_882_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln23_1_reg_1017 <= add_ln23_1_fu_642_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln25_reg_875 <= add_ln25_fu_316_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                empty_36_reg_870 <= empty_36_fu_306_p2;
                empty_37_reg_953_pp0_iter2_reg <= empty_37_reg_953;
                filterValue_reg_1028 <= m_axi_gmem_RDATA;
                filterValue_reg_1028_pp0_iter7_reg <= filterValue_reg_1028;
                gmem_addr_1_reg_1022 <= sext_ln31_fu_682_p1;
                iChannel_1_reg_858 <= iChannel_fu_118;
                icmp_ln25_reg_882 <= icmp_ln25_fu_322_p2;
                icmp_ln25_reg_882_pp0_iter1_reg <= icmp_ln25_reg_882;
                icmp_ln25_reg_882_pp0_iter2_reg <= icmp_ln25_reg_882_pp0_iter1_reg;
                icmp_ln25_reg_882_pp0_iter3_reg <= icmp_ln25_reg_882_pp0_iter2_reg;
                icmp_ln25_reg_882_pp0_iter4_reg <= icmp_ln25_reg_882_pp0_iter3_reg;
                icmp_ln25_reg_882_pp0_iter5_reg <= icmp_ln25_reg_882_pp0_iter4_reg;
                icmp_ln25_reg_882_pp0_iter6_reg <= icmp_ln25_reg_882_pp0_iter5_reg;
                icmp_ln25_reg_882_pp0_iter7_reg <= icmp_ln25_reg_882_pp0_iter6_reg;
                icmp_ln26_reg_896_pp0_iter1_reg <= icmp_ln26_reg_896;
                icmp_ln26_reg_896_pp0_iter2_reg <= icmp_ln26_reg_896_pp0_iter1_reg;
                indvar_flatten93_load_reg_865 <= indvar_flatten93_fu_122;
                select_ln23_4_reg_912_pp0_iter1_reg <= select_ln23_4_reg_912;
                select_ln23_4_reg_912_pp0_iter2_reg <= select_ln23_4_reg_912_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln25_fu_322_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                add_ln26_reg_920 <= add_ln26_fu_358_p2;
                cx_load_reg_886 <= cx_fu_106;
                icmp_ln26_reg_896 <= icmp_ln26_fu_333_p2;
                indvar_flatten_load_reg_891 <= indvar_flatten_fu_114;
                select_ln23_4_reg_912 <= select_ln23_4_fu_351_p3;
                select_ln23_reg_907 <= select_ln23_fu_338_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln25_reg_882_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                    cx_cast_reg_1006(31 downto 0) <= cx_cast_fu_567_p1(31 downto 0);
                gmem_addr_reg_1011 <= sext_ln30_fu_576_p1;
                p_mid137_reg_1000 <= grp_fu_482_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                empty_35_reg_932 <= grp_fu_344_p_dout0;
                empty_38_reg_938 <= grp_fu_348_p_dout0;
                empty_reg_974 <= grp_fu_453_p2;
                    p_cast8_mid145_cast_reg_837(31 downto 0) <= p_cast8_mid145_cast_fu_245_p1(31 downto 0);
                pixelValue_reg_1033 <= m_axi_gmem_RDATA;
                select_ln23_5_reg_943_pp0_iter2_reg <= select_ln23_5_reg_943;
                tmp2_reg_927 <= grp_fu_271_p_dout0;
                    tmp4_cast_mid167_cast_reg_848(31 downto 0) <= tmp4_cast_mid167_cast_fu_253_p1(31 downto 0);
                trunc_ln1_reg_1048 <= grp_fu_698_p2(51 downto 20);
                    zext_ln20_1_cast_reg_842(31 downto 0) <= zext_ln20_1_cast_fu_249_p1(31 downto 0);
                    zext_ln25_cast_reg_832(31 downto 0) <= zext_ln25_cast_fu_241_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln23_4_reg_912 = ap_const_lv1_0) and (icmp_ln26_reg_896 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                empty_37_reg_953 <= grp_fu_352_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln23_4_reg_912_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln26_reg_896_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                empty_39_reg_980 <= empty_39_fu_476_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln23_4_reg_912_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln25_reg_882_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_mid110_reg_990 <= grp_fu_457_p2;
                p_mid120_reg_995 <= p_mid120_fu_515_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln23_4_reg_912 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln25_reg_882 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                p_mid118_reg_969 <= grp_fu_413_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln25_reg_882 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                p_mid139_reg_963 <= grp_fu_363_p_dout0;
                tmp2_mid1_reg_958 <= grp_fu_356_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln23_4_reg_912_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln26_reg_896_pp0_iter1_reg = ap_const_lv1_1) and (icmp_ln25_reg_882_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_mid169_reg_985 <= p_mid169_fu_498_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((select_ln23_4_reg_912 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln25_reg_882 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_mid1_reg_948 <= p_mid1_fu_397_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln25_reg_882 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln23_5_reg_943 <= select_ln23_5_fu_390_p3;
            end if;
        end if;
    end process;
    zext_ln25_cast_reg_832(33 downto 32) <= "00";
    p_cast8_mid145_cast_reg_837(32) <= '0';
    zext_ln20_1_cast_reg_842(32) <= '0';
    tmp4_cast_mid167_cast_reg_848(32) <= '0';
    cx_cast_reg_1006(62 downto 32) <= "0000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to9, ap_done_pending_pp0, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_done_pending_pp0 = ap_const_logic_0) and (ap_idle_pp0_1to9 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    acc_1_fu_717_p2 <= std_logic_vector(unsigned(trunc_ln1_reg_1048) + unsigned(acc_fu_102));
    acc_out <= acc_fu_102;

    acc_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln25_reg_882_pp0_iter7_reg)
    begin
        if (((icmp_ln25_reg_882_pp0_iter7_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
            acc_out_ap_vld <= ap_const_logic_1;
        else 
            acc_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln23_1_fu_642_p2 <= std_logic_vector(unsigned(zext_ln23_3_fu_638_p1) + unsigned(zext_ln25_cast_reg_832));
    add_ln23_2_fu_658_p2 <= std_logic_vector(unsigned(zext_ln23_4_fu_654_p1) + unsigned(input_r));
    add_ln23_fu_548_p2 <= std_logic_vector(unsigned(zext_ln23_2_fu_544_p1) + unsigned(coeffs));
    add_ln25_1_fu_368_p2 <= std_logic_vector(unsigned(indvar_flatten93_load_reg_865) + unsigned(ap_const_lv96_1));
    add_ln25_fu_316_p0 <= iChannel_fu_118;
    add_ln25_fu_316_p2 <= std_logic_vector(signed(add_ln25_fu_316_p0) + signed(ap_const_lv32_1));
    add_ln26_1_fu_416_p2 <= std_logic_vector(unsigned(indvar_flatten_load_reg_891) + unsigned(ap_const_lv64_1));
    add_ln26_fu_358_p2 <= std_logic_vector(unsigned(select_ln23_fu_338_p3) + unsigned(ap_const_lv32_1));
    add_ln27_fu_410_p2 <= std_logic_vector(unsigned(select_ln23_5_fu_390_p3) + unsigned(ap_const_lv32_1));
    add_ln30_fu_570_p2 <= std_logic_vector(unsigned(cx_cast_fu_567_p1) + unsigned(sext_ln23_fu_563_p1));
    add_ln31_fu_677_p2 <= std_logic_vector(unsigned(cx_cast_reg_1006) + unsigned(sext_ln23_1_fu_673_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter8, m_axi_gmem_RVALID, ap_block_state7_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (m_axi_gmem_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter8, m_axi_gmem_RVALID, ap_block_state7_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (m_axi_gmem_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_io)));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_gmem_RVALID)
    begin
                ap_block_pp0_stage1_01001 <= ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (m_axi_gmem_RVALID = ap_const_logic_0));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, m_axi_gmem_ARREADY, m_axi_gmem_RVALID)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (m_axi_gmem_RVALID = ap_const_logic_0)) or ((m_axi_gmem_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, m_axi_gmem_ARREADY, m_axi_gmem_RVALID)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (m_axi_gmem_RVALID = ap_const_logic_0)) or ((m_axi_gmem_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;

        ap_block_state10_pp0_stage1_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage1_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state14_pp0_stage1_iter6_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state14_pp0_stage1_iter6 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;

        ap_block_state15_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage1_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state17_pp0_stage0_iter8_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state17_pp0_stage0_iter8 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;

        ap_block_state18_pp0_stage1_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage1_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_io_assign_proc : process(m_axi_gmem_ARREADY, icmp_ln25_reg_882_pp0_iter2_reg)
    begin
                ap_block_state7_io <= ((m_axi_gmem_ARREADY = ap_const_logic_0) and (icmp_ln25_reg_882_pp0_iter2_reg = ap_const_lv1_0));
    end process;

        ap_block_state7_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage1_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln25_fu_322_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln25_fu_322_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, icmp_ln25_reg_882_pp0_iter2_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln25_reg_882_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_done_pending_pp0_assign_proc : process(ap_loop_exit_ready, ap_loop_exit_ready_pp0_iter1_reg, ap_loop_exit_ready_pp0_iter2_reg, ap_loop_exit_ready_pp0_iter3_reg, ap_loop_exit_ready_pp0_iter4_reg, ap_loop_exit_ready_pp0_iter5_reg, ap_loop_exit_ready_pp0_iter6_reg, ap_loop_exit_ready_pp0_iter7_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (not(((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0) and (ap_loop_exit_ready = ap_const_logic_0)))) then 
            ap_done_pending_pp0 <= ap_const_logic_1;
        else 
            ap_done_pending_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to9_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to9 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to9 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    cx_cast_fu_567_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln23_5_reg_943_pp0_iter2_reg),63));
    empty_36_fu_306_p0 <= cy_fu_110;
    empty_36_fu_306_p2 <= std_logic_vector(signed(empty_36_fu_306_p0) + signed(select_ln20));
    empty_39_fu_476_p2 <= std_logic_vector(unsigned(tmp4_cast_fu_472_p1) + unsigned(zext_ln26_fu_461_p1));

    gmem_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, m_axi_gmem_ARREADY, ap_block_pp0_stage0, icmp_ln25_reg_882_pp0_iter2_reg, ap_block_pp0_stage1)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln25_reg_882_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)))) then 
            gmem_blk_n_AR <= m_axi_gmem_ARREADY;
        else 
            gmem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter8, ap_CS_fsm_pp0_stage1, m_axi_gmem_RVALID, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if ((((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1)))) then 
            gmem_blk_n_R <= m_axi_gmem_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_271_p_ce <= grp_fu_296_ce;
    grp_fu_271_p_din0 <= iChannel_fu_118;
    grp_fu_271_p_din1 <= inputWidth;

    grp_fu_296_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_296_ce <= ap_const_logic_1;
        else 
            grp_fu_296_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_301_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_301_ce <= ap_const_logic_1;
        else 
            grp_fu_301_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_311_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_311_ce <= ap_const_logic_1;
        else 
            grp_fu_311_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_344_p_ce <= grp_fu_301_ce;
    grp_fu_344_p_din0 <= iChannel_fu_118;
    grp_fu_344_p_din1 <= mul_ln20;
    grp_fu_348_p_ce <= grp_fu_311_ce;
    grp_fu_348_p_din0 <= cy_fu_110;
    grp_fu_348_p_din1 <= convWidth;
    grp_fu_352_p_ce <= grp_fu_364_ce;
    grp_fu_352_p_din0 <= empty_36_reg_870;
    grp_fu_352_p_din1 <= inputWidth;
    grp_fu_356_p_ce <= grp_fu_373_ce;
    grp_fu_356_p_din0 <= add_ln25_reg_875;
    grp_fu_356_p_din1 <= inputWidth;
    grp_fu_363_p_ce <= grp_fu_377_ce;
    grp_fu_363_p_din0 <= add_ln25_reg_875;
    grp_fu_363_p_din1 <= mul_ln20;

    grp_fu_364_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_364_ce <= ap_const_logic_1;
        else 
            grp_fu_364_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_373_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_373_ce <= ap_const_logic_1;
        else 
            grp_fu_373_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_377_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_377_ce <= ap_const_logic_1;
        else 
            grp_fu_377_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_401_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_401_ce <= ap_const_logic_1;
        else 
            grp_fu_401_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_413_p_ce <= grp_fu_401_ce;
    grp_fu_413_p_din0 <= add_ln26_reg_920;
    grp_fu_413_p_din1 <= convWidth;

    grp_fu_453_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_453_ce <= ap_const_logic_1;
        else 
            grp_fu_453_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_457_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_457_ce <= ap_const_logic_1;
        else 
            grp_fu_457_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_482_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_482_ce <= ap_const_logic_1;
        else 
            grp_fu_482_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_698_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            grp_fu_698_ce <= ap_const_logic_1;
        else 
            grp_fu_698_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln25_fu_322_p2 <= "1" when (indvar_flatten93_fu_122 = mul_ln3_1) else "0";
    icmp_ln26_fu_333_p2 <= "1" when (indvar_flatten_fu_114 = mul_ln3) else "0";
    icmp_ln27_fu_346_p1 <= convWidth;
    icmp_ln27_fu_346_p2 <= "1" when (cx_fu_106 = icmp_ln27_fu_346_p1) else "0";

    m_axi_gmem_ARADDR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, icmp_ln25_reg_882_pp0_iter2_reg, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, gmem_addr_reg_1011, gmem_addr_1_reg_1022)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
            m_axi_gmem_ARADDR <= gmem_addr_1_reg_1022;
        elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln25_reg_882_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem_ARADDR <= gmem_addr_reg_1011;
        else 
            m_axi_gmem_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_gmem_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_ARID <= ap_const_lv1_0;
    m_axi_gmem_ARLEN <= ap_const_lv32_1;
    m_axi_gmem_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_ARUSER <= ap_const_lv1_0;

    m_axi_gmem_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, icmp_ln25_reg_882_pp0_iter2_reg, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln25_reg_882_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
            m_axi_gmem_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_AWID <= ap_const_lv1_0;
    m_axi_gmem_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_AWVALID <= ap_const_logic_0;
    m_axi_gmem_BREADY <= ap_const_logic_0;

    m_axi_gmem_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter8, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
            m_axi_gmem_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_WDATA <= ap_const_lv32_0;
    m_axi_gmem_WID <= ap_const_lv1_0;
    m_axi_gmem_WLAST <= ap_const_logic_0;
    m_axi_gmem_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_WUSER <= ap_const_lv1_0;
    m_axi_gmem_WVALID <= ap_const_logic_0;
    or_ln23_fu_386_p2 <= (select_ln23_4_reg_912 or icmp_ln26_reg_896);
    p_cast11_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_38_reg_938),33));
    p_cast11_mid1_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid118_reg_969),33));
    p_cast7_fu_586_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_974),33));
    p_cast7_mid1_fu_598_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid137_reg_1000),33));
    p_cast8_fu_589_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_37_reg_953_pp0_iter2_reg),33));
    p_cast8_mid145_cast_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_cast8_mid145),33));
    p_cast8_mid1_fu_622_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid110_reg_990),33));
    p_mid120_fu_515_p2 <= std_logic_vector(unsigned(tmp4_cast_mid1_fu_511_p1) + unsigned(zext_ln23_1_fu_494_p1));
    p_mid169_fu_498_p2 <= std_logic_vector(unsigned(tmp4_cast_mid167_cast_reg_848) + unsigned(zext_ln23_5_fu_486_p1));
    p_mid1_fu_397_p2 <= std_logic_vector(signed(add_ln26_reg_920) + signed(select_ln20));
    select_ln23_1_fu_601_p3 <= 
        p_mid137_reg_1000 when (icmp_ln26_reg_896_pp0_iter2_reg(0) = '1') else 
        empty_reg_974;
    select_ln23_2_fu_489_p3 <= 
        p_mid139_reg_963 when (icmp_ln26_reg_896_pp0_iter1_reg(0) = '1') else 
        empty_35_reg_932;
    select_ln23_3_fu_615_p3 <= 
        tmp3_mid147_fu_610_p2 when (icmp_ln26_reg_896_pp0_iter2_reg(0) = '1') else 
        tmp3_fu_592_p2;
    select_ln23_4_fu_351_p3 <= 
        icmp_ln27_1 when (icmp_ln26_fu_333_p2(0) = '1') else 
        icmp_ln27_fu_346_p2;
    select_ln23_5_fu_390_p3 <= 
        ap_const_lv32_0 when (or_ln23_fu_386_p2(0) = '1') else 
        cx_load_reg_886;
    select_ln23_6_fu_524_p3 <= 
        zext_ln23_6_fu_521_p1 when (icmp_ln26_reg_896_pp0_iter1_reg(0) = '1') else 
        empty_39_reg_980;
    select_ln23_7_fu_530_p3 <= 
        p_mid120_reg_995 when (select_ln23_4_reg_912_pp0_iter1_reg(0) = '1') else 
        select_ln23_6_fu_524_p3;
    select_ln23_8_fu_631_p3 <= 
        tmp3_mid1_fu_625_p2 when (select_ln23_4_reg_912_pp0_iter2_reg(0) = '1') else 
        select_ln23_3_fu_615_p3;
    select_ln23_fu_338_p2 <= cy_fu_110;
    select_ln23_fu_338_p3 <= 
        ap_const_lv32_0 when (icmp_ln26_fu_333_p2(0) = '1') else 
        select_ln23_fu_338_p2;
    select_ln25_fu_381_p3 <= 
        add_ln25_reg_875 when (icmp_ln26_reg_896(0) = '1') else 
        iChannel_1_reg_858;
    select_ln26_1_fu_421_p3 <= 
        ap_const_lv64_1 when (icmp_ln26_reg_896(0) = '1') else 
        add_ln26_1_fu_416_p2;
    select_ln26_fu_405_p3 <= 
        add_ln26_reg_920 when (select_ln23_4_reg_912(0) = '1') else 
        select_ln23_reg_907;
        sext_ln23_1_fu_673_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln27_1_mid2_v_fu_663_p4),63));

        sext_ln23_fu_563_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln27_mid2_v_fu_553_p4),63));

    sext_ln27_1_mid2_v_fu_663_p4 <= add_ln23_2_fu_658_p2(63 downto 2);
    sext_ln27_1_mid2_v_v_v_v_v_fu_647_p3 <= (add_ln23_1_reg_1017 & ap_const_lv2_0);
    sext_ln27_mid2_v_fu_553_p4 <= add_ln23_fu_548_p2(63 downto 2);
    sext_ln27_mid2_v_v_v_v_v_fu_536_p3 <= (select_ln23_7_fu_530_p3 & ap_const_lv2_0);
        sext_ln30_fu_576_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln30_fu_570_p2),64));

        sext_ln31_fu_682_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln31_fu_677_p2),64));

    tmp3_fu_592_p2 <= std_logic_vector(unsigned(p_cast7_fu_586_p1) + unsigned(p_cast8_fu_589_p1));
    tmp3_mid147_fu_610_p2 <= std_logic_vector(unsigned(p_cast7_mid1_fu_598_p1) + unsigned(p_cast8_mid145_cast_reg_837));
    tmp3_mid1_fu_625_p2 <= std_logic_vector(unsigned(zext_ln23_fu_606_p1) + unsigned(p_cast8_mid1_fu_622_p1));
    tmp4_cast_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_fu_467_p2),34));
    tmp4_cast_mid167_cast_fu_253_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_cast_mid167),33));
    tmp4_cast_mid1_fu_511_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_mid1_fu_506_p2),34));
    tmp4_fu_467_p2 <= std_logic_vector(unsigned(zext_ln20_1_cast_reg_842) + unsigned(p_cast11_fu_464_p1));
    tmp4_mid1_fu_506_p2 <= std_logic_vector(unsigned(zext_ln20_1_cast_reg_842) + unsigned(p_cast11_mid1_fu_503_p1));
    zext_ln20_1_cast_fu_249_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln20_1),33));
    zext_ln23_1_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln23_2_fu_489_p3),34));
    zext_ln23_2_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln27_mid2_v_v_v_v_v_fu_536_p3),64));
    zext_ln23_3_fu_638_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln23_8_fu_631_p3),34));
    zext_ln23_4_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln27_1_mid2_v_v_v_v_v_fu_647_p3),64));
    zext_ln23_5_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid139_reg_963),33));
    zext_ln23_6_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_mid169_reg_985),34));
    zext_ln23_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln23_1_fu_601_p3),33));
    zext_ln25_cast_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln25),34));
    zext_ln26_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_35_reg_932),34));
end behav;
