// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Conv2D_HW_Conv2D_HW,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6938,HLS_SYN_LUT=5785,HLS_VERSION=2022_2}" *)

module Conv2D_HW (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 23'd1;
parameter    ap_ST_fsm_state2 = 23'd2;
parameter    ap_ST_fsm_state3 = 23'd4;
parameter    ap_ST_fsm_state4 = 23'd8;
parameter    ap_ST_fsm_state5 = 23'd16;
parameter    ap_ST_fsm_state6 = 23'd32;
parameter    ap_ST_fsm_state7 = 23'd64;
parameter    ap_ST_fsm_state8 = 23'd128;
parameter    ap_ST_fsm_state9 = 23'd256;
parameter    ap_ST_fsm_state10 = 23'd512;
parameter    ap_ST_fsm_state11 = 23'd1024;
parameter    ap_ST_fsm_state12 = 23'd2048;
parameter    ap_ST_fsm_state13 = 23'd4096;
parameter    ap_ST_fsm_state14 = 23'd8192;
parameter    ap_ST_fsm_state15 = 23'd16384;
parameter    ap_ST_fsm_state16 = 23'd32768;
parameter    ap_ST_fsm_state17 = 23'd65536;
parameter    ap_ST_fsm_state18 = 23'd131072;
parameter    ap_ST_fsm_state19 = 23'd262144;
parameter    ap_ST_fsm_state20 = 23'd524288;
parameter    ap_ST_fsm_state21 = 23'd1048576;
parameter    ap_ST_fsm_state22 = 23'd2097152;
parameter    ap_ST_fsm_state23 = 23'd4194304;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [22:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_r;
wire   [63:0] output_r;
wire   [63:0] coeffs;
wire   [31:0] numChannels;
wire   [31:0] numFilters;
wire   [31:0] inputWidth;
wire   [31:0] inputHeight;
wire   [31:0] convWidth;
wire   [31:0] convHeight;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state18;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state23;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state15;
reg  signed [31:0] convHeight_read_reg_471;
reg   [31:0] convWidth_read_reg_477;
reg   [31:0] inputHeight_read_reg_485;
reg   [31:0] inputWidth_read_reg_491;
reg   [31:0] numFilters_read_reg_498;
reg  signed [31:0] numChannels_read_reg_503;
reg   [63:0] coeffs_read_reg_509;
reg   [63:0] output_r_read_reg_514;
reg   [63:0] input_r_read_reg_519;
wire    ap_CS_fsm_state2;
wire   [63:0] grp_fu_248_p2;
reg   [63:0] mul_ln3_reg_540;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire  signed [31:0] sub_fu_266_p2;
reg  signed [31:0] sub_reg_556;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire  signed [31:0] sub6_fu_287_p2;
reg   [31:0] sub6_reg_573;
wire    ap_CS_fsm_state8;
wire  signed [31:0] grp_fu_271_p2;
reg   [31:0] mul_ln20_reg_581;
wire   [95:0] grp_fu_260_p2;
reg   [95:0] mul_ln3_1_reg_587;
wire   [63:0] grp_fu_281_p2;
reg   [63:0] mul_ln3_2_reg_592;
wire   [0:0] icmp_ln27_fu_292_p2;
reg   [0:0] icmp_ln27_reg_597;
wire   [63:0] add_ln20_fu_305_p2;
reg   [63:0] add_ln20_reg_605;
wire    ap_CS_fsm_state9;
wire  signed [31:0] select_ln20_fu_322_p3;
reg   [31:0] select_ln20_reg_610;
wire   [0:0] icmp_ln20_fu_300_p2;
wire  signed [31:0] select_ln20_1_fu_336_p3;
reg  signed [31:0] select_ln20_1_reg_618;
wire  signed [31:0] grp_fu_344_p2;
reg  signed [31:0] mul_ln20_1_reg_625;
wire    ap_CS_fsm_state11;
wire   [31:0] grp_fu_348_p2;
reg   [31:0] mul_ln20_2_reg_630;
wire    ap_CS_fsm_state13;
wire  signed [31:0] grp_fu_352_p2;
reg  signed [31:0] mul_ln20_3_reg_635;
wire   [31:0] grp_fu_356_p2;
reg   [31:0] empty_40_reg_640;
reg   [63:0] gmem_addr_reg_645;
wire    ap_CS_fsm_state14;
wire   [31:0] grp_fu_363_p2;
reg   [31:0] mul_ln20_4_reg_651;
wire   [31:0] grp_fu_413_p2;
reg   [31:0] p_mid143_reg_657;
wire   [31:0] add_ln22_fu_422_p2;
reg   [31:0] add_ln22_reg_665;
wire    ap_CS_fsm_state16;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_start;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_done;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_idle;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_ready;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WVALID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WDATA;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WSTRB;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WLAST;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WID;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARVALID;
wire   [63:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARADDR;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARID;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARLEN;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARSIZE;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARBURST;
wire   [1:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARLOCK;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARCACHE;
wire   [2:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARPROT;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARQOS;
wire   [3:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARREGION;
wire   [0:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARUSER;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_RREADY;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_BREADY;
wire   [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_acc_out;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_acc_out_ap_vld;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_271_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_271_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_271_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_344_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_344_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_344_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_348_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_348_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_348_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_352_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_352_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_352_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_356_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_356_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_356_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_363_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_363_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_363_p_ce;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_413_p_din0;
wire  signed [31:0] grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_413_p_din1;
wire    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_413_p_ce;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg   [31:0] x_reg_193;
reg    grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_start_reg;
wire   [0:0] icmp_ln22_fu_417_p2;
wire    ap_CS_fsm_state17;
wire  signed [63:0] sext_ln22_fu_403_p1;
reg   [31:0] y_fu_108;
wire   [31:0] add_ln21_fu_428_p2;
reg   [31:0] iFilter_fu_112;
reg   [63:0] indvar_flatten106_fu_116;
wire   [31:0] grp_fu_248_p0;
wire   [31:0] grp_fu_248_p1;
wire   [31:0] grp_fu_260_p0;
wire   [63:0] grp_fu_260_p1;
reg  signed [31:0] grp_fu_271_p0;
reg  signed [31:0] grp_fu_271_p1;
wire   [31:0] grp_fu_281_p0;
wire   [31:0] grp_fu_281_p1;
wire   [0:0] icmp_ln21_fu_317_p2;
wire   [31:0] add_ln20_1_fu_330_p2;
reg  signed [31:0] grp_fu_344_p0;
reg  signed [31:0] grp_fu_344_p1;
wire    ap_CS_fsm_state10;
reg  signed [31:0] grp_fu_348_p0;
reg  signed [31:0] grp_fu_348_p1;
wire    ap_CS_fsm_state12;
reg  signed [31:0] grp_fu_352_p0;
reg  signed [31:0] grp_fu_352_p1;
reg  signed [31:0] grp_fu_356_p0;
reg  signed [31:0] grp_fu_356_p1;
reg  signed [31:0] grp_fu_363_p0;
reg  signed [31:0] grp_fu_363_p1;
wire   [32:0] p_cast_fu_367_p1;
wire   [32:0] zext_ln20_fu_360_p1;
wire   [32:0] empty_41_fu_370_p2;
wire   [34:0] tmp_fu_376_p3;
wire   [63:0] p_cast14_fu_384_p1;
wire   [63:0] empty_42_fu_388_p2;
wire   [61:0] trunc_ln_fu_393_p4;
reg  signed [31:0] grp_fu_413_p0;
reg  signed [31:0] grp_fu_413_p1;
reg    grp_fu_271_ce;
reg    grp_fu_344_ce;
reg    grp_fu_348_ce;
reg    grp_fu_352_ce;
reg    grp_fu_356_ce;
reg    grp_fu_363_ce;
reg    grp_fu_413_ce;
reg   [22:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire   [63:0] grp_fu_248_p00;
wire   [63:0] grp_fu_248_p10;
wire   [95:0] grp_fu_260_p00;
wire   [95:0] grp_fu_260_p10;
wire   [63:0] grp_fu_281_p00;
wire   [63:0] grp_fu_281_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 23'd1;
#0 grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_start_reg = 1'b0;
end

Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6 grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_start),
    .ap_done(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_done),
    .ap_idle(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_idle),
    .ap_ready(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_ready),
    .m_axi_gmem_AWVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .inputWidth(inputWidth_read_reg_491),
    .inputHeight(inputHeight_read_reg_485),
    .mul_ln20(mul_ln20_reg_581),
    .select_ln20(select_ln20_reg_610),
    .convWidth(convWidth_read_reg_477),
    .zext_ln20_1(mul_ln20_4_reg_651),
    .mul_ln3_1(mul_ln3_1_reg_587),
    .mul_ln3(mul_ln3_reg_540),
    .p_cast8_mid145(p_mid143_reg_657),
    .tmp4_cast_mid167(mul_ln20_4_reg_651),
    .icmp_ln27_1(icmp_ln27_reg_597),
    .coeffs(coeffs_read_reg_509),
    .zext_ln25(x_reg_193),
    .input_r(input_r_read_reg_519),
    .acc_out(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_acc_out),
    .acc_out_ap_vld(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_acc_out_ap_vld),
    .grp_fu_271_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_271_p_din0),
    .grp_fu_271_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_271_p_din1),
    .grp_fu_271_p_dout0(grp_fu_271_p2),
    .grp_fu_271_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_271_p_ce),
    .grp_fu_344_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_344_p_din0),
    .grp_fu_344_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_344_p_din1),
    .grp_fu_344_p_dout0(grp_fu_344_p2),
    .grp_fu_344_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_344_p_ce),
    .grp_fu_348_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_348_p_din0),
    .grp_fu_348_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_348_p_din1),
    .grp_fu_348_p_dout0(grp_fu_348_p2),
    .grp_fu_348_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_348_p_ce),
    .grp_fu_352_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_352_p_din0),
    .grp_fu_352_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_352_p_din1),
    .grp_fu_352_p_dout0(grp_fu_352_p2),
    .grp_fu_352_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_352_p_ce),
    .grp_fu_356_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_356_p_din0),
    .grp_fu_356_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_356_p_din1),
    .grp_fu_356_p_dout0(grp_fu_356_p2),
    .grp_fu_356_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_356_p_ce),
    .grp_fu_363_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_363_p_din0),
    .grp_fu_363_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_363_p_din1),
    .grp_fu_363_p_dout0(grp_fu_363_p2),
    .grp_fu_363_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_363_p_ce),
    .grp_fu_413_p_din0(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_413_p_din0),
    .grp_fu_413_p_din1(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_413_p_din1),
    .grp_fu_413_p_dout0(grp_fu_413_p2),
    .grp_fu_413_p_ce(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_413_p_ce)
);

Conv2D_HW_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r(input_r),
    .output_r(output_r),
    .coeffs(coeffs),
    .numChannels(numChannels),
    .numFilters(numFilters),
    .inputWidth(inputWidth),
    .inputHeight(inputHeight),
    .convWidth(convWidth),
    .convHeight(convHeight),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

Conv2D_HW_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARADDR),
    .I_ARLEN(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_addr_reg_645),
    .I_AWLEN(sub6_reg_573),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_acc_out),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

Conv2D_HW_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U30(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_248_p0),
    .din1(grp_fu_248_p1),
    .ce(1'b1),
    .dout(grp_fu_248_p2)
);

Conv2D_HW_mul_32ns_64ns_96_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 96 ))
mul_32ns_64ns_96_5_1_U31(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_260_p0),
    .din1(grp_fu_260_p1),
    .ce(1'b1),
    .dout(grp_fu_260_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U32(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_271_p0),
    .din1(grp_fu_271_p1),
    .ce(grp_fu_271_ce),
    .dout(grp_fu_271_p2)
);

Conv2D_HW_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U33(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_281_p0),
    .din1(grp_fu_281_p1),
    .ce(1'b1),
    .dout(grp_fu_281_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U34(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_344_p0),
    .din1(grp_fu_344_p1),
    .ce(grp_fu_344_ce),
    .dout(grp_fu_344_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U35(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_348_p0),
    .din1(grp_fu_348_p1),
    .ce(grp_fu_348_ce),
    .dout(grp_fu_348_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U36(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_352_p0),
    .din1(grp_fu_352_p1),
    .ce(grp_fu_352_ce),
    .dout(grp_fu_352_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U37(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_356_p0),
    .din1(grp_fu_356_p1),
    .ce(grp_fu_356_ce),
    .dout(grp_fu_356_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U38(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_363_p0),
    .din1(grp_fu_363_p1),
    .ce(grp_fu_363_ce),
    .dout(grp_fu_363_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U39(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_413_p0),
    .din1(grp_fu_413_p1),
    .ce(grp_fu_413_ce),
    .dout(grp_fu_413_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln22_fu_417_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16))) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_start_reg <= 1'b1;
        end else if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_ready == 1'b1)) begin
            grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        iFilter_fu_112 <= 32'd0;
    end else if (((icmp_ln22_fu_417_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        iFilter_fu_112 <= select_ln20_1_reg_618;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten106_fu_116 <= 64'd0;
    end else if (((icmp_ln22_fu_417_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        indvar_flatten106_fu_116 <= add_ln20_reg_605;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        x_reg_193 <= 32'd0;
    end else if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        x_reg_193 <= add_ln22_reg_665;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_108 <= 32'd0;
    end else if (((icmp_ln22_fu_417_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        y_fu_108 <= add_ln21_fu_428_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln20_reg_605 <= add_ln20_fu_305_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        add_ln22_reg_665 <= add_ln22_fu_422_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        coeffs_read_reg_509 <= coeffs;
        convHeight_read_reg_471 <= convHeight;
        convWidth_read_reg_477 <= convWidth;
        inputHeight_read_reg_485 <= inputHeight;
        inputWidth_read_reg_491 <= inputWidth;
        input_r_read_reg_519 <= input_r;
        numChannels_read_reg_503 <= numChannels;
        numFilters_read_reg_498 <= numFilters;
        output_r_read_reg_514 <= output_r;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        empty_40_reg_640 <= grp_fu_356_p2;
        mul_ln20_2_reg_630 <= grp_fu_348_p2;
        mul_ln20_3_reg_635 <= grp_fu_352_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        gmem_addr_reg_645 <= sext_ln22_fu_403_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        icmp_ln27_reg_597 <= icmp_ln27_fu_292_p2;
        mul_ln20_reg_581 <= grp_fu_271_p2;
        mul_ln3_1_reg_587 <= grp_fu_260_p2;
        mul_ln3_2_reg_592 <= grp_fu_281_p2;
        sub6_reg_573 <= sub6_fu_287_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        mul_ln20_1_reg_625 <= grp_fu_344_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        mul_ln20_4_reg_651 <= grp_fu_363_p2;
        p_mid143_reg_657 <= grp_fu_413_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln3_reg_540 <= grp_fu_248_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln20_fu_300_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        select_ln20_1_reg_618 <= select_ln20_1_fu_336_p3;
        select_ln20_reg_610 <= select_ln20_fu_322_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sub_reg_556 <= sub_fu_266_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((gmem_AWREADY == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_WREADY == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((gmem_BVALID == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln20_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln20_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((icmp_ln22_fu_417_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16)))) begin
        gmem_ARVALID = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((icmp_ln22_fu_417_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state16)))) begin
        gmem_RREADY = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_271_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_271_p_ce;
    end else begin
        grp_fu_271_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_271_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_271_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_271_p0 = convHeight_read_reg_471;
    end else begin
        grp_fu_271_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_271_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_271_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_271_p1 = convWidth_read_reg_477;
    end else begin
        grp_fu_271_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_344_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_344_p_ce;
    end else begin
        grp_fu_344_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_344_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_344_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_344_p0 = sub6_reg_573;
    end else begin
        grp_fu_344_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_344_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_344_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_344_p1 = select_ln20_1_reg_618;
    end else begin
        grp_fu_344_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_348_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_348_p_ce;
    end else begin
        grp_fu_348_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_348_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_348_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_348_p0 = mul_ln20_1_reg_625;
    end else begin
        grp_fu_348_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_348_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_348_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_348_p1 = sub_reg_556;
    end else begin
        grp_fu_348_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_352_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_352_p_ce;
    end else begin
        grp_fu_352_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_352_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_352_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_352_p0 = select_ln20_1_reg_618;
    end else begin
        grp_fu_352_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_352_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_352_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_352_p1 = numChannels_read_reg_503;
    end else begin
        grp_fu_352_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_356_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_356_p_ce;
    end else begin
        grp_fu_356_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_356_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_356_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_356_p0 = select_ln20_reg_610;
    end else begin
        grp_fu_356_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_356_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_356_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_356_p1 = sub6_reg_573;
    end else begin
        grp_fu_356_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_363_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_363_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state14) | ((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15)))) begin
        grp_fu_363_ce = 1'b1;
    end else begin
        grp_fu_363_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_363_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_363_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_363_p0 = mul_ln20_3_reg_635;
    end else begin
        grp_fu_363_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_363_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_363_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_363_p1 = mul_ln20_reg_581;
    end else begin
        grp_fu_363_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_413_ce = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_413_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state14) | ((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15)))) begin
        grp_fu_413_ce = 1'b1;
    end else begin
        grp_fu_413_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_413_p0 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_413_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_413_p0 = select_ln20_reg_610;
    end else begin
        grp_fu_413_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_413_p1 = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_grp_fu_413_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_413_p1 = inputWidth_read_reg_491;
    end else begin
        grp_fu_413_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln20_fu_300_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln22_fu_417_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln20_1_fu_330_p2 = (iFilter_fu_112 + 32'd1);

assign add_ln20_fu_305_p2 = (indvar_flatten106_fu_116 + 64'd1);

assign add_ln21_fu_428_p2 = (select_ln20_reg_610 + 32'd1);

assign add_ln22_fu_422_p2 = (x_reg_193 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_41_fu_370_p2 = (p_cast_fu_367_p1 + zext_ln20_fu_360_p1);

assign empty_42_fu_388_p2 = (p_cast14_fu_384_p1 + output_r_read_reg_514);

assign grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_start = grp_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6_fu_205_ap_start_reg;

assign grp_fu_248_p0 = grp_fu_248_p00;

assign grp_fu_248_p00 = $unsigned(convHeight_read_reg_471);

assign grp_fu_248_p1 = grp_fu_248_p10;

assign grp_fu_248_p10 = convWidth_read_reg_477;

assign grp_fu_260_p0 = grp_fu_260_p00;

assign grp_fu_260_p00 = $unsigned(numChannels_read_reg_503);

assign grp_fu_260_p1 = grp_fu_260_p10;

assign grp_fu_260_p10 = mul_ln3_reg_540;

assign grp_fu_281_p0 = grp_fu_281_p00;

assign grp_fu_281_p00 = numFilters_read_reg_498;

assign grp_fu_281_p1 = grp_fu_281_p10;

assign grp_fu_281_p10 = $unsigned(sub_reg_556);

assign icmp_ln20_fu_300_p2 = ((indvar_flatten106_fu_116 == mul_ln3_2_reg_592) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_317_p2 = ((y_fu_108 == sub_reg_556) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_417_p2 = ((x_reg_193 == sub6_reg_573) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_292_p2 = ((convWidth_read_reg_477 == 32'd0) ? 1'b1 : 1'b0);

assign p_cast14_fu_384_p1 = tmp_fu_376_p3;

assign p_cast_fu_367_p1 = empty_40_reg_640;

assign select_ln20_1_fu_336_p3 = ((icmp_ln21_fu_317_p2[0:0] == 1'b1) ? add_ln20_1_fu_330_p2 : iFilter_fu_112);

assign select_ln20_fu_322_p3 = ((icmp_ln21_fu_317_p2[0:0] == 1'b1) ? 32'd0 : y_fu_108);

assign sext_ln22_fu_403_p1 = $signed(trunc_ln_fu_393_p4);

assign sub6_fu_287_p2 = ($signed(inputWidth_read_reg_491) + $signed(32'd4294967294));

assign sub_fu_266_p2 = ($signed(inputHeight_read_reg_485) + $signed(32'd4294967294));

assign tmp_fu_376_p3 = {{empty_41_fu_370_p2}, {2'd0}};

assign trunc_ln_fu_393_p4 = {{empty_42_fu_388_p2[63:2]}};

assign zext_ln20_fu_360_p1 = mul_ln20_2_reg_630;

endmodule //Conv2D_HW
