// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        inputWidth,
        inputHeight,
        mul_ln20,
        select_ln20,
        convWidth,
        zext_ln20_1,
        mul_ln3_1,
        mul_ln3,
        p_cast8_mid145,
        tmp4_cast_mid167,
        icmp_ln27_1,
        coeffs,
        zext_ln25,
        input_r,
        acc_out,
        acc_out_ap_vld,
        grp_fu_271_p_din0,
        grp_fu_271_p_din1,
        grp_fu_271_p_dout0,
        grp_fu_271_p_ce,
        grp_fu_344_p_din0,
        grp_fu_344_p_din1,
        grp_fu_344_p_dout0,
        grp_fu_344_p_ce,
        grp_fu_348_p_din0,
        grp_fu_348_p_din1,
        grp_fu_348_p_dout0,
        grp_fu_348_p_ce,
        grp_fu_352_p_din0,
        grp_fu_352_p_din1,
        grp_fu_352_p_dout0,
        grp_fu_352_p_ce,
        grp_fu_356_p_din0,
        grp_fu_356_p_din1,
        grp_fu_356_p_dout0,
        grp_fu_356_p_ce,
        grp_fu_363_p_din0,
        grp_fu_363_p_din1,
        grp_fu_363_p_dout0,
        grp_fu_363_p_ce,
        grp_fu_413_p_din0,
        grp_fu_413_p_din1,
        grp_fu_413_p_dout0,
        grp_fu_413_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [31:0] m_axi_gmem_WDATA;
output  [3:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [31:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [31:0] inputWidth;
input  [31:0] inputHeight;
input  [31:0] mul_ln20;
input  [31:0] select_ln20;
input  [31:0] convWidth;
input  [31:0] zext_ln20_1;
input  [95:0] mul_ln3_1;
input  [63:0] mul_ln3;
input  [31:0] p_cast8_mid145;
input  [31:0] tmp4_cast_mid167;
input  [0:0] icmp_ln27_1;
input  [63:0] coeffs;
input  [31:0] zext_ln25;
input  [63:0] input_r;
output  [31:0] acc_out;
output   acc_out_ap_vld;
output  [31:0] grp_fu_271_p_din0;
output  [31:0] grp_fu_271_p_din1;
input  [31:0] grp_fu_271_p_dout0;
output   grp_fu_271_p_ce;
output  [31:0] grp_fu_344_p_din0;
output  [31:0] grp_fu_344_p_din1;
input  [31:0] grp_fu_344_p_dout0;
output   grp_fu_344_p_ce;
output  [31:0] grp_fu_348_p_din0;
output  [31:0] grp_fu_348_p_din1;
input  [31:0] grp_fu_348_p_dout0;
output   grp_fu_348_p_ce;
output  [31:0] grp_fu_352_p_din0;
output  [31:0] grp_fu_352_p_din1;
input  [31:0] grp_fu_352_p_dout0;
output   grp_fu_352_p_ce;
output  [31:0] grp_fu_356_p_din0;
output  [31:0] grp_fu_356_p_din1;
input  [31:0] grp_fu_356_p_dout0;
output   grp_fu_356_p_ce;
output  [31:0] grp_fu_363_p_din0;
output  [31:0] grp_fu_363_p_din1;
input  [31:0] grp_fu_363_p_dout0;
output   grp_fu_363_p_ce;
output  [31:0] grp_fu_413_p_din0;
output  [31:0] grp_fu_413_p_din1;
input  [31:0] grp_fu_413_p_dout0;
output   grp_fu_413_p_ce;

reg ap_idle;
reg m_axi_gmem_ARVALID;
reg[63:0] m_axi_gmem_ARADDR;
reg m_axi_gmem_RREADY;
reg acc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_state10_pp0_stage1_iter4;
wire    ap_block_state12_pp0_stage1_iter5;
reg    ap_block_state14_pp0_stage1_iter6;
wire    ap_block_state16_pp0_stage1_iter7;
wire    ap_block_state18_pp0_stage1_iter8;
wire    ap_block_state20_pp0_stage1_iter9;
reg    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln25_fu_322_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln25_reg_882;
reg   [0:0] icmp_ln25_reg_882_pp0_iter2_reg;
reg    gmem_blk_n_R;
wire    ap_block_pp0_stage1;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
reg    ap_block_state7_io;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state11_pp0_stage0_iter5;
wire    ap_block_state13_pp0_stage0_iter6;
wire    ap_block_state15_pp0_stage0_iter7;
reg    ap_block_state17_pp0_stage0_iter8;
wire    ap_block_state19_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_11001;
wire   [33:0] zext_ln25_cast_fu_241_p1;
reg   [33:0] zext_ln25_cast_reg_832;
wire   [32:0] p_cast8_mid145_cast_fu_245_p1;
reg   [32:0] p_cast8_mid145_cast_reg_837;
wire   [32:0] zext_ln20_1_cast_fu_249_p1;
reg   [32:0] zext_ln20_1_cast_reg_842;
wire   [32:0] tmp4_cast_mid167_cast_fu_253_p1;
reg   [32:0] tmp4_cast_mid167_cast_reg_848;
reg    ap_block_pp0_stage1_11001;
reg  signed [31:0] iChannel_1_reg_858;
reg   [95:0] indvar_flatten93_load_reg_865;
wire  signed [31:0] empty_36_fu_306_p2;
reg  signed [31:0] empty_36_reg_870;
wire  signed [31:0] add_ln25_fu_316_p2;
reg  signed [31:0] add_ln25_reg_875;
reg   [0:0] icmp_ln25_reg_882_pp0_iter1_reg;
reg   [0:0] icmp_ln25_reg_882_pp0_iter3_reg;
reg   [0:0] icmp_ln25_reg_882_pp0_iter4_reg;
reg   [0:0] icmp_ln25_reg_882_pp0_iter5_reg;
reg   [0:0] icmp_ln25_reg_882_pp0_iter6_reg;
reg   [0:0] icmp_ln25_reg_882_pp0_iter7_reg;
reg   [31:0] cx_load_reg_886;
reg   [63:0] indvar_flatten_load_reg_891;
wire   [0:0] icmp_ln26_fu_333_p2;
reg   [0:0] icmp_ln26_reg_896;
reg   [0:0] icmp_ln26_reg_896_pp0_iter1_reg;
reg   [0:0] icmp_ln26_reg_896_pp0_iter2_reg;
wire   [31:0] select_ln23_fu_338_p3;
reg   [31:0] select_ln23_reg_907;
wire   [0:0] select_ln23_4_fu_351_p3;
reg   [0:0] select_ln23_4_reg_912;
reg   [0:0] select_ln23_4_reg_912_pp0_iter1_reg;
reg   [0:0] select_ln23_4_reg_912_pp0_iter2_reg;
wire  signed [31:0] add_ln26_fu_358_p2;
reg  signed [31:0] add_ln26_reg_920;
reg  signed [31:0] tmp2_reg_927;
reg   [31:0] empty_35_reg_932;
reg   [31:0] empty_38_reg_938;
wire   [31:0] select_ln23_5_fu_390_p3;
reg   [31:0] select_ln23_5_reg_943;
reg   [31:0] select_ln23_5_reg_943_pp0_iter2_reg;
wire  signed [31:0] p_mid1_fu_397_p2;
reg  signed [31:0] p_mid1_reg_948;
reg   [31:0] empty_37_reg_953;
reg   [31:0] empty_37_reg_953_pp0_iter2_reg;
reg  signed [31:0] tmp2_mid1_reg_958;
reg   [31:0] p_mid139_reg_963;
reg   [31:0] p_mid118_reg_969;
wire   [31:0] grp_fu_453_p2;
reg   [31:0] empty_reg_974;
wire   [33:0] empty_39_fu_476_p2;
reg   [33:0] empty_39_reg_980;
wire   [32:0] p_mid169_fu_498_p2;
reg   [32:0] p_mid169_reg_985;
wire   [31:0] grp_fu_457_p2;
reg   [31:0] p_mid110_reg_990;
wire   [33:0] p_mid120_fu_515_p2;
reg   [33:0] p_mid120_reg_995;
wire   [31:0] grp_fu_482_p2;
reg   [31:0] p_mid137_reg_1000;
wire   [62:0] cx_cast_fu_567_p1;
reg   [62:0] cx_cast_reg_1006;
reg   [63:0] gmem_addr_reg_1011;
wire   [33:0] add_ln23_1_fu_642_p2;
reg   [33:0] add_ln23_1_reg_1017;
reg   [63:0] gmem_addr_1_reg_1022;
reg  signed [31:0] filterValue_reg_1028;
reg  signed [31:0] filterValue_reg_1028_pp0_iter7_reg;
reg  signed [31:0] pixelValue_reg_1033;
reg   [31:0] trunc_ln1_reg_1048;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter3_stage0;
wire  signed [63:0] sext_ln30_fu_576_p1;
wire  signed [63:0] sext_ln31_fu_682_p1;
reg   [31:0] acc_fu_102;
wire   [31:0] acc_1_fu_717_p2;
wire    ap_loop_init;
reg   [31:0] cx_fu_106;
wire   [31:0] add_ln27_fu_410_p2;
reg   [31:0] cy_fu_110;
wire   [31:0] select_ln26_fu_405_p3;
reg   [63:0] indvar_flatten_fu_114;
wire   [63:0] select_ln26_1_fu_421_p3;
reg   [31:0] iChannel_fu_118;
wire   [31:0] select_ln25_fu_381_p3;
reg   [95:0] indvar_flatten93_fu_122;
wire   [95:0] add_ln25_1_fu_368_p2;
reg    ap_block_pp0_stage1_01001;
wire  signed [31:0] empty_36_fu_306_p0;
wire  signed [31:0] add_ln25_fu_316_p0;
wire  signed [31:0] select_ln23_fu_338_p2;
wire  signed [31:0] icmp_ln27_fu_346_p1;
wire   [0:0] icmp_ln27_fu_346_p2;
wire   [0:0] or_ln23_fu_386_p2;
wire   [63:0] add_ln26_1_fu_416_p2;
wire   [32:0] p_cast11_fu_464_p1;
wire   [32:0] tmp4_fu_467_p2;
wire   [33:0] tmp4_cast_fu_472_p1;
wire   [33:0] zext_ln26_fu_461_p1;
wire   [31:0] select_ln23_2_fu_489_p3;
wire   [32:0] zext_ln23_5_fu_486_p1;
wire   [32:0] p_cast11_mid1_fu_503_p1;
wire   [32:0] tmp4_mid1_fu_506_p2;
wire   [33:0] tmp4_cast_mid1_fu_511_p1;
wire   [33:0] zext_ln23_1_fu_494_p1;
wire   [33:0] zext_ln23_6_fu_521_p1;
wire   [33:0] select_ln23_6_fu_524_p3;
wire   [33:0] select_ln23_7_fu_530_p3;
wire   [35:0] sext_ln27_mid2_v_v_v_v_v_fu_536_p3;
wire   [63:0] zext_ln23_2_fu_544_p1;
wire   [63:0] add_ln23_fu_548_p2;
wire   [61:0] sext_ln27_mid2_v_fu_553_p4;
wire  signed [62:0] sext_ln23_fu_563_p1;
wire   [62:0] add_ln30_fu_570_p2;
wire   [32:0] p_cast7_fu_586_p1;
wire   [32:0] p_cast8_fu_589_p1;
wire   [31:0] select_ln23_1_fu_601_p3;
wire   [32:0] p_cast7_mid1_fu_598_p1;
wire   [32:0] tmp3_mid147_fu_610_p2;
wire   [32:0] tmp3_fu_592_p2;
wire   [32:0] zext_ln23_fu_606_p1;
wire   [32:0] p_cast8_mid1_fu_622_p1;
wire   [32:0] tmp3_mid1_fu_625_p2;
wire   [32:0] select_ln23_3_fu_615_p3;
wire   [32:0] select_ln23_8_fu_631_p3;
wire   [33:0] zext_ln23_3_fu_638_p1;
wire   [35:0] sext_ln27_1_mid2_v_v_v_v_v_fu_647_p3;
wire   [63:0] zext_ln23_4_fu_654_p1;
wire   [63:0] add_ln23_2_fu_658_p2;
wire   [61:0] sext_ln27_1_mid2_v_fu_663_p4;
wire  signed [62:0] sext_ln23_1_fu_673_p1;
wire   [62:0] add_ln31_fu_677_p2;
wire   [51:0] grp_fu_698_p2;
reg    grp_fu_296_ce;
reg    grp_fu_301_ce;
reg    grp_fu_311_ce;
reg    grp_fu_364_ce;
reg    grp_fu_373_ce;
reg    grp_fu_377_ce;
reg    grp_fu_401_ce;
reg    grp_fu_453_ce;
reg    grp_fu_457_ce;
reg    grp_fu_482_ce;
reg    grp_fu_698_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to9;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp2_reg_927),
    .din1(inputHeight),
    .ce(grp_fu_453_ce),
    .dout(grp_fu_453_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_mid1_reg_948),
    .din1(inputWidth),
    .ce(grp_fu_457_ce),
    .dout(grp_fu_457_p2)
);

Conv2D_HW_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp2_mid1_reg_958),
    .din1(inputHeight),
    .ce(grp_fu_482_ce),
    .dout(grp_fu_482_p2)
);

Conv2D_HW_mul_32s_32s_52_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 52 ))
mul_32s_32s_52_2_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(pixelValue_reg_1033),
    .din1(filterValue_reg_1028_pp0_iter7_reg),
    .ce(grp_fu_698_ce),
    .dout(grp_fu_698_p2)
);

Conv2D_HW_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_fu_102 <= 32'd0;
    end else if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        acc_fu_102 <= acc_1_fu_717_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            cx_fu_106 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln25_reg_882 == 1'd0))) begin
            cx_fu_106 <= add_ln27_fu_410_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            cy_fu_110 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln25_reg_882 == 1'd0))) begin
            cy_fu_110 <= select_ln26_fu_405_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            iChannel_fu_118 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln25_reg_882 == 1'd0))) begin
            iChannel_fu_118 <= select_ln25_fu_381_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten93_fu_122 <= 96'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln25_reg_882 == 1'd0))) begin
            indvar_flatten93_fu_122 <= add_ln25_1_fu_368_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_114 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln25_reg_882 == 1'd0))) begin
            indvar_flatten_fu_114 <= select_ln26_1_fu_421_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln25_reg_882_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln23_1_reg_1017 <= add_ln23_1_fu_642_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln25_reg_875 <= add_ln25_fu_316_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        empty_36_reg_870 <= empty_36_fu_306_p2;
        empty_37_reg_953_pp0_iter2_reg <= empty_37_reg_953;
        filterValue_reg_1028 <= m_axi_gmem_RDATA;
        filterValue_reg_1028_pp0_iter7_reg <= filterValue_reg_1028;
        gmem_addr_1_reg_1022 <= sext_ln31_fu_682_p1;
        iChannel_1_reg_858 <= iChannel_fu_118;
        icmp_ln25_reg_882 <= icmp_ln25_fu_322_p2;
        icmp_ln25_reg_882_pp0_iter1_reg <= icmp_ln25_reg_882;
        icmp_ln25_reg_882_pp0_iter2_reg <= icmp_ln25_reg_882_pp0_iter1_reg;
        icmp_ln25_reg_882_pp0_iter3_reg <= icmp_ln25_reg_882_pp0_iter2_reg;
        icmp_ln25_reg_882_pp0_iter4_reg <= icmp_ln25_reg_882_pp0_iter3_reg;
        icmp_ln25_reg_882_pp0_iter5_reg <= icmp_ln25_reg_882_pp0_iter4_reg;
        icmp_ln25_reg_882_pp0_iter6_reg <= icmp_ln25_reg_882_pp0_iter5_reg;
        icmp_ln25_reg_882_pp0_iter7_reg <= icmp_ln25_reg_882_pp0_iter6_reg;
        icmp_ln26_reg_896_pp0_iter1_reg <= icmp_ln26_reg_896;
        icmp_ln26_reg_896_pp0_iter2_reg <= icmp_ln26_reg_896_pp0_iter1_reg;
        indvar_flatten93_load_reg_865 <= indvar_flatten93_fu_122;
        select_ln23_4_reg_912_pp0_iter1_reg <= select_ln23_4_reg_912;
        select_ln23_4_reg_912_pp0_iter2_reg <= select_ln23_4_reg_912_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln25_fu_322_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        add_ln26_reg_920 <= add_ln26_fu_358_p2;
        cx_load_reg_886 <= cx_fu_106;
        icmp_ln26_reg_896 <= icmp_ln26_fu_333_p2;
        indvar_flatten_load_reg_891 <= indvar_flatten_fu_114;
        select_ln23_4_reg_912 <= select_ln23_4_fu_351_p3;
        select_ln23_reg_907 <= select_ln23_fu_338_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln25_reg_882_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        cx_cast_reg_1006[31 : 0] <= cx_cast_fu_567_p1[31 : 0];
        gmem_addr_reg_1011 <= sext_ln30_fu_576_p1;
        p_mid137_reg_1000 <= grp_fu_482_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_35_reg_932 <= grp_fu_344_p_dout0;
        empty_38_reg_938 <= grp_fu_348_p_dout0;
        empty_reg_974 <= grp_fu_453_p2;
        p_cast8_mid145_cast_reg_837[31 : 0] <= p_cast8_mid145_cast_fu_245_p1[31 : 0];
        pixelValue_reg_1033 <= m_axi_gmem_RDATA;
        select_ln23_5_reg_943_pp0_iter2_reg <= select_ln23_5_reg_943;
        tmp2_reg_927 <= grp_fu_271_p_dout0;
        tmp4_cast_mid167_cast_reg_848[31 : 0] <= tmp4_cast_mid167_cast_fu_253_p1[31 : 0];
        trunc_ln1_reg_1048 <= {{grp_fu_698_p2[51:20]}};
        zext_ln20_1_cast_reg_842[31 : 0] <= zext_ln20_1_cast_fu_249_p1[31 : 0];
        zext_ln25_cast_reg_832[31 : 0] <= zext_ln25_cast_fu_241_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln23_4_reg_912 == 1'd0) & (icmp_ln26_reg_896 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        empty_37_reg_953 <= grp_fu_352_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln23_4_reg_912_pp0_iter1_reg == 1'd0) & (icmp_ln26_reg_896_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        empty_39_reg_980 <= empty_39_fu_476_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln23_4_reg_912_pp0_iter1_reg == 1'd1) & (icmp_ln25_reg_882_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_mid110_reg_990 <= grp_fu_457_p2;
        p_mid120_reg_995 <= p_mid120_fu_515_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln23_4_reg_912 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln25_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        p_mid118_reg_969 <= grp_fu_413_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln25_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        p_mid139_reg_963 <= grp_fu_363_p_dout0;
        tmp2_mid1_reg_958 <= grp_fu_356_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln23_4_reg_912_pp0_iter1_reg == 1'd0) & (icmp_ln26_reg_896_pp0_iter1_reg == 1'd1) & (icmp_ln25_reg_882_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_mid169_reg_985 <= p_mid169_fu_498_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((select_ln23_4_reg_912 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln25_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_mid1_reg_948 <= p_mid1_fu_397_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln25_reg_882 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        select_ln23_5_reg_943 <= select_ln23_5_fu_390_p3;
    end
end

always @ (*) begin
    if (((icmp_ln25_reg_882_pp0_iter7_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        acc_out_ap_vld = 1'b1;
    end else begin
        acc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln25_fu_322_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln25_reg_882_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter8_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to9 = 1'b1;
    end else begin
        ap_idle_pp0_1to9 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln25_reg_882_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_296_ce = 1'b1;
    end else begin
        grp_fu_296_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_301_ce = 1'b1;
    end else begin
        grp_fu_301_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_311_ce = 1'b1;
    end else begin
        grp_fu_311_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_364_ce = 1'b1;
    end else begin
        grp_fu_364_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_373_ce = 1'b1;
    end else begin
        grp_fu_373_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_377_ce = 1'b1;
    end else begin
        grp_fu_377_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_401_ce = 1'b1;
    end else begin
        grp_fu_401_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_453_ce = 1'b1;
    end else begin
        grp_fu_453_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_457_ce = 1'b1;
    end else begin
        grp_fu_457_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_482_ce = 1'b1;
    end else begin
        grp_fu_482_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_698_ce = 1'b1;
    end else begin
        grp_fu_698_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_1_reg_1022;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln25_reg_882_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_ARADDR = gmem_addr_reg_1011;
    end else begin
        m_axi_gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln25_reg_882_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to9 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_fu_717_p2 = (trunc_ln1_reg_1048 + acc_fu_102);

assign acc_out = acc_fu_102;

assign add_ln23_1_fu_642_p2 = (zext_ln23_3_fu_638_p1 + zext_ln25_cast_reg_832);

assign add_ln23_2_fu_658_p2 = (zext_ln23_4_fu_654_p1 + input_r);

assign add_ln23_fu_548_p2 = (zext_ln23_2_fu_544_p1 + coeffs);

assign add_ln25_1_fu_368_p2 = (indvar_flatten93_load_reg_865 + 96'd1);

assign add_ln25_fu_316_p0 = iChannel_fu_118;

assign add_ln25_fu_316_p2 = ($signed(add_ln25_fu_316_p0) + $signed(32'd1));

assign add_ln26_1_fu_416_p2 = (indvar_flatten_load_reg_891 + 64'd1);

assign add_ln26_fu_358_p2 = (select_ln23_fu_338_p3 + 32'd1);

assign add_ln27_fu_410_p2 = (select_ln23_5_fu_390_p3 + 32'd1);

assign add_ln30_fu_570_p2 = ($signed(cx_cast_fu_567_p1) + $signed(sext_ln23_fu_563_p1));

assign add_ln31_fu_677_p2 = ($signed(cx_cast_reg_1006) + $signed(sext_ln23_1_fu_673_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state7_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter8 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state7_io)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter6 == 1'b1) & (m_axi_gmem_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)) | ((m_axi_gmem_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)) | ((m_axi_gmem_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)));
end

assign ap_block_state10_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_pp0_stage1_iter6 = (m_axi_gmem_RVALID == 1'b0);
end

assign ap_block_state15_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state17_pp0_stage0_iter8 = (m_axi_gmem_RVALID == 1'b0);
end

assign ap_block_state18_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_io = ((m_axi_gmem_ARREADY == 1'b0) & (icmp_ln25_reg_882_pp0_iter2_reg == 1'd0));
end

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign cx_cast_fu_567_p1 = select_ln23_5_reg_943_pp0_iter2_reg;

assign empty_36_fu_306_p0 = cy_fu_110;

assign empty_36_fu_306_p2 = ($signed(empty_36_fu_306_p0) + $signed(select_ln20));

assign empty_39_fu_476_p2 = (tmp4_cast_fu_472_p1 + zext_ln26_fu_461_p1);

assign grp_fu_271_p_ce = grp_fu_296_ce;

assign grp_fu_271_p_din0 = iChannel_fu_118;

assign grp_fu_271_p_din1 = inputWidth;

assign grp_fu_344_p_ce = grp_fu_301_ce;

assign grp_fu_344_p_din0 = iChannel_fu_118;

assign grp_fu_344_p_din1 = mul_ln20;

assign grp_fu_348_p_ce = grp_fu_311_ce;

assign grp_fu_348_p_din0 = cy_fu_110;

assign grp_fu_348_p_din1 = convWidth;

assign grp_fu_352_p_ce = grp_fu_364_ce;

assign grp_fu_352_p_din0 = empty_36_reg_870;

assign grp_fu_352_p_din1 = inputWidth;

assign grp_fu_356_p_ce = grp_fu_373_ce;

assign grp_fu_356_p_din0 = add_ln25_reg_875;

assign grp_fu_356_p_din1 = inputWidth;

assign grp_fu_363_p_ce = grp_fu_377_ce;

assign grp_fu_363_p_din0 = add_ln25_reg_875;

assign grp_fu_363_p_din1 = mul_ln20;

assign grp_fu_413_p_ce = grp_fu_401_ce;

assign grp_fu_413_p_din0 = add_ln26_reg_920;

assign grp_fu_413_p_din1 = convWidth;

assign icmp_ln25_fu_322_p2 = ((indvar_flatten93_fu_122 == mul_ln3_1) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_333_p2 = ((indvar_flatten_fu_114 == mul_ln3) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_346_p1 = convWidth;

assign icmp_ln27_fu_346_p2 = ((cx_fu_106 == icmp_ln27_fu_346_p1) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd1;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 32'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 4'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign or_ln23_fu_386_p2 = (select_ln23_4_reg_912 | icmp_ln26_reg_896);

assign p_cast11_fu_464_p1 = empty_38_reg_938;

assign p_cast11_mid1_fu_503_p1 = p_mid118_reg_969;

assign p_cast7_fu_586_p1 = empty_reg_974;

assign p_cast7_mid1_fu_598_p1 = p_mid137_reg_1000;

assign p_cast8_fu_589_p1 = empty_37_reg_953_pp0_iter2_reg;

assign p_cast8_mid145_cast_fu_245_p1 = p_cast8_mid145;

assign p_cast8_mid1_fu_622_p1 = p_mid110_reg_990;

assign p_mid120_fu_515_p2 = (tmp4_cast_mid1_fu_511_p1 + zext_ln23_1_fu_494_p1);

assign p_mid169_fu_498_p2 = (tmp4_cast_mid167_cast_reg_848 + zext_ln23_5_fu_486_p1);

assign p_mid1_fu_397_p2 = ($signed(add_ln26_reg_920) + $signed(select_ln20));

assign select_ln23_1_fu_601_p3 = ((icmp_ln26_reg_896_pp0_iter2_reg[0:0] == 1'b1) ? p_mid137_reg_1000 : empty_reg_974);

assign select_ln23_2_fu_489_p3 = ((icmp_ln26_reg_896_pp0_iter1_reg[0:0] == 1'b1) ? p_mid139_reg_963 : empty_35_reg_932);

assign select_ln23_3_fu_615_p3 = ((icmp_ln26_reg_896_pp0_iter2_reg[0:0] == 1'b1) ? tmp3_mid147_fu_610_p2 : tmp3_fu_592_p2);

assign select_ln23_4_fu_351_p3 = ((icmp_ln26_fu_333_p2[0:0] == 1'b1) ? icmp_ln27_1 : icmp_ln27_fu_346_p2);

assign select_ln23_5_fu_390_p3 = ((or_ln23_fu_386_p2[0:0] == 1'b1) ? 32'd0 : cx_load_reg_886);

assign select_ln23_6_fu_524_p3 = ((icmp_ln26_reg_896_pp0_iter1_reg[0:0] == 1'b1) ? zext_ln23_6_fu_521_p1 : empty_39_reg_980);

assign select_ln23_7_fu_530_p3 = ((select_ln23_4_reg_912_pp0_iter1_reg[0:0] == 1'b1) ? p_mid120_reg_995 : select_ln23_6_fu_524_p3);

assign select_ln23_8_fu_631_p3 = ((select_ln23_4_reg_912_pp0_iter2_reg[0:0] == 1'b1) ? tmp3_mid1_fu_625_p2 : select_ln23_3_fu_615_p3);

assign select_ln23_fu_338_p2 = cy_fu_110;

assign select_ln23_fu_338_p3 = ((icmp_ln26_fu_333_p2[0:0] == 1'b1) ? 32'd0 : select_ln23_fu_338_p2);

assign select_ln25_fu_381_p3 = ((icmp_ln26_reg_896[0:0] == 1'b1) ? add_ln25_reg_875 : iChannel_1_reg_858);

assign select_ln26_1_fu_421_p3 = ((icmp_ln26_reg_896[0:0] == 1'b1) ? 64'd1 : add_ln26_1_fu_416_p2);

assign select_ln26_fu_405_p3 = ((select_ln23_4_reg_912[0:0] == 1'b1) ? add_ln26_reg_920 : select_ln23_reg_907);

assign sext_ln23_1_fu_673_p1 = $signed(sext_ln27_1_mid2_v_fu_663_p4);

assign sext_ln23_fu_563_p1 = $signed(sext_ln27_mid2_v_fu_553_p4);

assign sext_ln27_1_mid2_v_fu_663_p4 = {{add_ln23_2_fu_658_p2[63:2]}};

assign sext_ln27_1_mid2_v_v_v_v_v_fu_647_p3 = {{add_ln23_1_reg_1017}, {2'd0}};

assign sext_ln27_mid2_v_fu_553_p4 = {{add_ln23_fu_548_p2[63:2]}};

assign sext_ln27_mid2_v_v_v_v_v_fu_536_p3 = {{select_ln23_7_fu_530_p3}, {2'd0}};

assign sext_ln30_fu_576_p1 = $signed(add_ln30_fu_570_p2);

assign sext_ln31_fu_682_p1 = $signed(add_ln31_fu_677_p2);

assign tmp3_fu_592_p2 = (p_cast7_fu_586_p1 + p_cast8_fu_589_p1);

assign tmp3_mid147_fu_610_p2 = (p_cast7_mid1_fu_598_p1 + p_cast8_mid145_cast_reg_837);

assign tmp3_mid1_fu_625_p2 = (zext_ln23_fu_606_p1 + p_cast8_mid1_fu_622_p1);

assign tmp4_cast_fu_472_p1 = tmp4_fu_467_p2;

assign tmp4_cast_mid167_cast_fu_253_p1 = tmp4_cast_mid167;

assign tmp4_cast_mid1_fu_511_p1 = tmp4_mid1_fu_506_p2;

assign tmp4_fu_467_p2 = (zext_ln20_1_cast_reg_842 + p_cast11_fu_464_p1);

assign tmp4_mid1_fu_506_p2 = (zext_ln20_1_cast_reg_842 + p_cast11_mid1_fu_503_p1);

assign zext_ln20_1_cast_fu_249_p1 = zext_ln20_1;

assign zext_ln23_1_fu_494_p1 = select_ln23_2_fu_489_p3;

assign zext_ln23_2_fu_544_p1 = sext_ln27_mid2_v_v_v_v_v_fu_536_p3;

assign zext_ln23_3_fu_638_p1 = select_ln23_8_fu_631_p3;

assign zext_ln23_4_fu_654_p1 = sext_ln27_1_mid2_v_v_v_v_v_fu_647_p3;

assign zext_ln23_5_fu_486_p1 = p_mid139_reg_963;

assign zext_ln23_6_fu_521_p1 = p_mid169_reg_985;

assign zext_ln23_fu_606_p1 = select_ln23_1_fu_601_p3;

assign zext_ln25_cast_fu_241_p1 = zext_ln25;

assign zext_ln26_fu_461_p1 = empty_35_reg_932;

always @ (posedge ap_clk) begin
    zext_ln25_cast_reg_832[33:32] <= 2'b00;
    p_cast8_mid145_cast_reg_837[32] <= 1'b0;
    zext_ln20_1_cast_reg_842[32] <= 1'b0;
    tmp4_cast_mid167_cast_reg_848[32] <= 1'b0;
    cx_cast_reg_1006[62:32] <= 31'b0000000000000000000000000000000;
end

endmodule //Conv2D_HW_Conv2D_HW_Pipeline_VITIS_LOOP_25_4_VITIS_LOOP_26_5_VITIS_LOOP_27_6
